CREATE SCHEMA IF NOT EXISTS EJOURNAL;

CREATE TABLE IF NOT EXISTS EJOURNAL.USERS (
  ID INT NOT NULL AUTO_INCREMENT ,
  ROLE INT NOT NULL ,
  NAME VARCHAR(45) NULL ,
  SURNAME VARCHAR(45) NULL ,
  BIRTHDATE DATETIME NULL ,
  SEX INT NULL,
  LOGIN VARCHAR(45) NOT NULL ,
  PASSWORD VARCHAR(45) NOT NULL ,
  PRIMARY KEY (ID) ,
INSERT INTO EJOURNAL.USERS VALUES (NULL, 2, 'ADMIN', 'ADMIN', NULL, 1, 'admin', '827ccb0eea8a706c4c34a16891f84e7b');

CREATE TABLE IF NOT EXISTS EJOURNAL.ENTITIESLOG (
  ID INT NOT NULL AUTO_INCREMENT ,
  ENTITYID INT NOT NULL ,
  ENTITYTYPE INT NOT NULL ,
  DATE DATETIME NULL ,
  ACTION INT NOT NULL,
  COMMENT VARCHAR(255) NULL ,
  USERID INT NOT NULL,
  PRIMARY KEY (ID));
ALTER TABLE EJOURNAL.ENTITIESLOG ADD FOREIGN KEY (USERID) REFERENCES EJOURNAL.USERS(ID);

CREATE TABLE IF NOT EXISTS EJOURNAL.SUBJECTS (
  ID INT NOT NULL AUTO_INCREMENT ,
  NAME VARCHAR(255) NOT NULL,
  SHORTNAME VARCHAR(12) NULL,
  PRIMARY KEY (ID));
  
CREATE TABLE IF NOT EXISTS EJOURNAL.TEACHERS (
  ID INT NOT NULL AUTO_INCREMENT ,
  USERID INT NOT NULL,
  START_WORK DATE NULL,
  EXPERIENCE INT NULL,
  PRIMARY KEY (ID));
ALTER TABLE EJOURNAL.TEACHERS ADD FOREIGN KEY (USERID) REFERENCES EJOURNAL.USERS(ID); 